[2023-04-13T15:08:15.625+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.save_greeting manual__2023-04-13T15:08:12.432452+00:00 [queued]>
[2023-04-13T15:08:15.636+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.save_greeting manual__2023-04-13T15:08:12.432452+00:00 [queued]>
[2023-04-13T15:08:15.637+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T15:08:15.638+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T15:08:15.638+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T15:08:15.659+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): save_greeting> on 2023-04-13 15:08:12.432452+00:00
[2023-04-13T15:08:15.663+0000] {standard_task_runner.py:55} INFO - Started process 1656 to run task
[2023-04-13T15:08:15.666+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'save_greeting', 'manual__2023-04-13T15:08:12.432452+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpaknqbwaq']
[2023-04-13T15:08:15.669+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask save_greeting
[2023-04-13T15:08:15.740+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.save_greeting manual__2023-04-13T15:08:12.432452+00:00 [running]> on host 6a1c33c9be4a
[2023-04-13T15:08:15.824+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=save_greeting
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T15:08:12.432452+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T15:08:12.432452+00:00
[2023-04-13T15:08:15.840+0000] {logging_mixin.py:137} INFO - Hello World 2023-04-13 15:08:14.696791
[2023-04-13T15:08:15.847+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 30, in save_greeting
    with open(path, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/trungdang/Desktop/greeting.txt'
[2023-04-13T15:08:15.862+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=first_dag, task_id=save_greeting, execution_date=20230413T150812, start_date=20230413T150815, end_date=20230413T150815
[2023-04-13T15:08:15.884+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 80 for task save_greeting ([Errno 2] No such file or directory: '/Users/trungdang/Desktop/greeting.txt'; 1656)
[2023-04-13T15:08:15.919+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T15:08:15.979+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
