[2023-04-13T14:55:18.543+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.process_greeting manual__2023-04-13T14:55:16.188667+00:00 [queued]>
[2023-04-13T14:55:18.664+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.process_greeting manual__2023-04-13T14:55:16.188667+00:00 [queued]>
[2023-04-13T14:55:18.665+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:55:18.665+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T14:55:18.666+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:55:18.685+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): process_greeting> on 2023-04-13 14:55:16.188667+00:00
[2023-04-13T14:55:18.689+0000] {standard_task_runner.py:55} INFO - Started process 1244 to run task
[2023-04-13T14:55:18.692+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'process_greeting', 'manual__2023-04-13T14:55:16.188667+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpsqckfqru']
[2023-04-13T14:55:18.694+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask process_greeting
[2023-04-13T14:55:18.761+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.process_greeting manual__2023-04-13T14:55:16.188667+00:00 [running]> on host 6a1c33c9be4a
[2023-04-13T14:55:18.840+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=process_greeting
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T14:55:16.188667+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T14:55:16.188667+00:00
[2023-04-13T14:55:18.854+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 16, in process_greeting
    return str(gr[0] + datetime.now())
TypeError: can only concatenate str (not "datetime.datetime") to str
[2023-04-13T14:55:18.863+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=first_dag, task_id=process_greeting, execution_date=20230413T145516, start_date=20230413T145518, end_date=20230413T145518
[2023-04-13T14:55:18.875+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task process_greeting (can only concatenate str (not "datetime.datetime") to str; 1244)
[2023-04-13T14:55:18.905+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T14:55:18.928+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
