[2023-04-13T14:28:50.391+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.get_datetime scheduled__2023-04-13T14:27:00+00:00 [queued]>
[2023-04-13T14:28:50.507+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.get_datetime scheduled__2023-04-13T14:27:00+00:00 [queued]>
[2023-04-13T14:28:50.508+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:28:50.508+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T14:28:50.509+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:28:50.526+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get_datetime> on 2023-04-13 14:27:00+00:00
[2023-04-13T14:28:50.530+0000] {standard_task_runner.py:55} INFO - Started process 493 to run task
[2023-04-13T14:28:50.533+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'get_datetime', 'scheduled__2023-04-13T14:27:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpyow7i3k3']
[2023-04-13T14:28:50.535+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask get_datetime
[2023-04-13T14:28:50.600+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.get_datetime scheduled__2023-04-13T14:27:00+00:00 [running]> on host 6a1c33c9be4a
[2023-04-13T14:28:50.679+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=get_datetime
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T14:27:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T14:27:00+00:00
[2023-04-13T14:28:50.681+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-13T14:28:50.682+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'Echo %date%-%time%']
[2023-04-13T14:28:50.691+0000] {subprocess.py:86} INFO - Output:
[2023-04-13T14:28:50.692+0000] {subprocess.py:93} INFO - /bin/bash: line 1: Echo: command not found
[2023-04-13T14:28:50.693+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-04-13T14:28:50.703+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-04-13T14:28:50.708+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=first_dag, task_id=get_datetime, execution_date=20230413T142700, start_date=20230413T142850, end_date=20230413T142850
[2023-04-13T14:28:50.721+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task get_datetime (Bash command failed. The command returned a non-zero exit code 127.; 493)
[2023-04-13T14:28:50.746+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T14:28:50.771+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
