[2023-04-13T14:55:18.547+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.process_greeting scheduled__2023-04-13T14:54:00+00:00 [queued]>
[2023-04-13T14:55:18.686+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.process_greeting scheduled__2023-04-13T14:54:00+00:00 [queued]>
[2023-04-13T14:55:18.687+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:55:18.687+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T14:55:18.688+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T14:55:18.706+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): process_greeting> on 2023-04-13 14:54:00+00:00
[2023-04-13T14:55:18.710+0000] {standard_task_runner.py:55} INFO - Started process 1245 to run task
[2023-04-13T14:55:18.713+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'process_greeting', 'scheduled__2023-04-13T14:54:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpyhn4jo1z']
[2023-04-13T14:55:18.715+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask process_greeting
[2023-04-13T14:55:18.780+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.process_greeting scheduled__2023-04-13T14:54:00+00:00 [running]> on host 6a1c33c9be4a
[2023-04-13T14:55:18.859+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=process_greeting
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T14:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T14:54:00+00:00
[2023-04-13T14:55:18.873+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 16, in process_greeting
    return str(gr[0] + datetime.now())
TypeError: can only concatenate str (not "datetime.datetime") to str
[2023-04-13T14:55:18.880+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=first_dag, task_id=process_greeting, execution_date=20230413T145400, start_date=20230413T145518, end_date=20230413T145518
[2023-04-13T14:55:18.891+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task process_greeting (can only concatenate str (not "datetime.datetime") to str; 1245)
[2023-04-13T14:55:18.926+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T14:55:18.950+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
